# Generated by Django 4.2.11 on 2024-04-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanage', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('Close', 'Close')], default='Open', max_length=5),
        ),
    ]
