# Generated by Django 4.2.11 on 2024-05-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanage', '0004_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='answer',
            new_name='chat',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='conversation_time',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='question',
        ),
    ]
