# Generated by Django 5.0.6 on 2024-05-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanage', '0007_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
