# Generated by Django 4.2.3 on 2024-05-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dsmanage", "0007_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
