# Generated by Django 5.0.6 on 2024-05-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanage', '0008_transaction_profit_alter_profile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='profit',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='curr_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
