# Generated by Django 5.0.6 on 2024-05-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmanage', '0010_transaction_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
