# Generated by Django 4.2.3 on 2024-05-13 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dsmanage", "0008_alter_profile_balance"),
        ("dsmanage", "0011_transaction_points"),
    ]

    operations = []
